export const POPUPS = [
    {
        "name": "Edge Esmeralda 2025",
        "slug": "edge-esmeralda",
        "tagline": "A month-long, multigenerational popup village for people building the future.",
        "location": "Healdsburg, California",
        "passes_description": "Not sure which week to pick? You can buy now and switch your week closer to the event—lock in your spot today!",
        "image_url": "https://cdn.prod.website-files.com/67475a01312f8d8225a6b46e/6751bf69596d8a1e1a99d291_half-banner-min.jpg",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-21T03:00:00",
        "clickable_in_portal": true,
        "visible_in_portal": true,
        "requires_approval": true,
        "created_at": null,
        "updated_at": "2024-12-05T20:41:49",
        "id": 1
    }
]

export const PRODUCTS = [
    {
        "name": "<2 yo - Month",
        "slug": "month-kid-free",
        "price": 0,
        "compare_price": 0,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "baby",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-21T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 23
    },
    {
        "name": "Month",
        "slug": "month-spouse",
        "price": 1957,
        "compare_price": 1957,
        "popup_city_id": 1,
        "description": null,
        "category": "month",
        "attendee_category": "spouse",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-21T03:00:00",
        "is_active": true,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 11
    },
    {
        "name": "Month",
        "slug": "month",
        "price": 2609,
        "compare_price": 2609,
        "popup_city_id": 1,
        "description": null,
        "category": "month",
        "attendee_category": "main",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-21T03:00:00",
        "is_active": true,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 10
    },
    {
        "name": "Month with Camp",
        "slug": "month-kid-camp",
        "price": 1200,
        "compare_price": 1200,
        "popup_city_id": 1,
        "description": null,
        "category": "month",
        "attendee_category": "kid",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-21T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 29
    },
    {
        "name": "Month without Camp",
        "slug": "month-teen-no-camp",
        "price": 1044,
        "compare_price": 1044,
        "popup_city_id": 1,
        "description": null,
        "category": "month",
        "attendee_category": "teen",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-21T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 34
    },
    {
        "name": "Month without Camp",
        "slug": "month-kid-no-camp",
        "price": 0,
        "compare_price": 0,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "kid",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-21T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 24
    },
    {
        "name": "Patron Pass",
        "slug": "patreon",
        "price": 7500,
        "compare_price": 7500,
        "popup_city_id": 1,
        "description": null,
        "category": "patreon",
        "attendee_category": "main",
        "start_date": null,
        "end_date": null,
        "is_active": true,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 9
    },
    {
        "name": "Week 1",
        "slug": "week1",
        "price": 960,
        "compare_price": 960,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "main",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-01T03:00:00",
        "is_active": true,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 1
    },
    {
        "name": "Week 1",
        "slug": "week1-spouse",
        "price": 720,
        "compare_price": 720,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "spouse",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-01T03:00:00",
        "is_active": true,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 5
    },
    {
        "name": "Week 1 with Camp",
        "slug": "week1-kid-camp",
        "price": 450,
        "compare_price": 450,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "kid",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-01T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 25
    },
    {
        "name": "Week 1 without Camp",
        "slug": "week1-teen",
        "price": 384,
        "compare_price": 384,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "teen",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-01T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 30
    },
    {
        "name": "Week 2",
        "slug": "week1-spouse",
        "price": 720,
        "compare_price": 720,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "spouse",
        "start_date": "2025-06-01T03:00:00",
        "end_date": "2025-06-08T03:00:00",
        "is_active": true,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 6
    },
    {
        "name": "Week 2",
        "slug": "week2",
        "price": 960,
        "compare_price": 960,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "main",
        "start_date": "2025-06-01T03:00:00",
        "end_date": "2025-06-08T03:00:00",
        "is_active": true,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 2
    },
    {
        "name": "Week 2 with Camp",
        "slug": "week2-kid-camp",
        "price": 450,
        "compare_price": 450,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "kid",
        "start_date": "2025-06-01T03:00:00",
        "end_date": "2025-06-08T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 26
    },
    {
        "name": "Week 2 without Camp",
        "slug": "week2-teen",
        "price": 384,
        "compare_price": 384,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "teen",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-01T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 31
    },
    {
        "name": "Week 3",
        "slug": "week1-spouse",
        "price": 720,
        "compare_price": 720,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "spouse",
        "start_date": "2025-06-08T03:00:00",
        "end_date": "2025-06-15T03:00:00",
        "is_active": true,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 7
    },
    {
        "name": "Week 3",
        "slug": "week3",
        "price": 960,
        "compare_price": 960,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "main",
        "start_date": "2025-06-08T03:00:00",
        "end_date": "2025-06-15T03:00:00",
        "is_active": true,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 3
    },
    {
        "name": "Week 3 with Camp",
        "slug": "week3-kid-camp",
        "price": 450,
        "compare_price": 450,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "kid",
        "start_date": "2025-06-08T03:00:00",
        "end_date": "2025-06-15T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 27
    },
    {
        "name": "Week 3 without Camp",
        "slug": "week3-teen",
        "price": 384,
        "compare_price": 384,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "teen",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-01T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 32
    },
    {
        "name": "Week 4",
        "slug": "week1-spouse",
        "price": 720,
        "compare_price": 720,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "spouse",
        "start_date": "2025-06-15T03:00:00",
        "end_date": "2025-06-21T03:00:00",
        "is_active": true,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 8
    },
    {
        "name": "Week 4",
        "slug": "week4",
        "price": 960,
        "compare_price": 960,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "main",
        "start_date": "2025-06-15T03:00:00",
        "end_date": "2025-06-21T03:00:00",
        "is_active": true,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 4
    },
    {
        "name": "Week 4 with Camp",
        "slug": "week4-kid-camp",
        "price": 450,
        "compare_price": 450,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "kid",
        "start_date": "2025-06-15T03:00:00",
        "end_date": "2025-06-21T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 28
    },
    {
        "name": "Week 4 without Camp",
        "slug": "week4-teen",
        "price": 384,
        "compare_price": 384,
        "popup_city_id": 1,
        "description": null,
        "category": "week",
        "attendee_category": "teen",
        "start_date": "2025-05-24T03:00:00",
        "end_date": "2025-06-01T03:00:00",
        "is_active": false,
        "exclusive": false,
        "created_at": null,
        "updated_at": null,
        "id": 33
    }
]


export const APPLICATION_DATA = {
    "first_name": "esmeralda",
    "last_name": "Test",
    "telegram": "cholecococo",
    "organization": null,
    "role": null,
    "gender": "Male",
    "age": "25-34",
    "social_media": null,
    "residence": null,
    "local_resident": null,
    "eth_address": null,
    "duration": null,
    "video_url": "test",
    "payment_capacity": null,
    "github_profile": null,
    "minting_link": null,
    "hackathon_interest": null,
    "host_session": null,
    "personal_goals": null,
    "referral": null,
    "info_not_shared": null,
    "investor": null,
    "is_renter": false,
    "booking_confirmation": null,
    "brings_spouse": null,
    "spouse_info": null,
    "spouse_email": null,
    "brings_kids": null,
    "kids_info": null,
    "builder_boolean": false,
    "builder_description": null,
    "scholarship_request": false,
    "scholarship_details": "",
    "scholarship_video_url": null,
    "requested_discount": false,
    "status": "accepted",
    "created_at": "2025-01-20T19:51:28.011126",
    "updated_at": "2025-02-24T13:52:34.283152",
    "citizen_id": 2,
    "popup_city_id": 1,
    "email": "joel@muvinai.com",
    "submitted_at": "2025-01-20T19:51:30.526380",
    "id": 58,
    "attendees": [
        {
            "application_id": 58,
            "name": "test",
            "category": "main",
            "email": "joel@muvinai.com",
            "created_at": "2025-01-20T19:51:28.025706",
            "updated_at": "2025-02-13T14:46:45.395689",
            "id": 112,
            "products": []
        }
    ],
    "discount_assigned": null,
    "products": null,
    "credit": 0
}
