const APPLICATION_DATA = {
    "first_name": "Choleco",
    "last_name": "Checkout",
    "telegram": "CholecoCheckout",
    "organization": null,
    "role": null,
    "gender": "Male",
    "age": "25-34",
    "social_media": null,
    "residence": null,
    "local_resident": null,
    "eth_address": null,
    "duration": null,
    "video_url": "test",
    "payment_capacity": null,
    "github_profile": null,
    "minting_link": null,
    "hackathon_interest": null,
    "host_session": null,
    "personal_goals": null,
    "referral": null,
    "info_not_shared": null,
    "investor": null,
    "is_renter": false,
    "booking_confirmation": null,
    "brings_spouse": null,
    "spouse_info": null,
    "spouse_email": null,
    "brings_kids": null,
    "kids_info": null,
    "builder_boolean": false,
    "builder_description": null,
    "scholarship_request": false,
    "scholarship_details": "",
    "scholarship_video_url": null,
    "requested_discount": false,
    "status": "accepted",
    "created_at": "2025-01-20T19:51:28.011126",
    "updated_at": "2025-02-24T13:52:34.283152",
    "citizen_id": 2,
    "popup_city_id": 1,
    "email": "joel@muvinai.com",
    "submitted_at": "2025-01-20T19:51:30.526380",
    "id": 58,
    "attendees": [
        {
            "application_id": 58,
            "name": "test",
            "category": "main",
            "email": "joel@muvinai.com",
            "created_at": "2025-01-20T19:51:28.025706",
            "updated_at": "2025-02-13T14:46:45.395689",
            "id": 112,
            "products": []
        },
    ],
    "discount_assigned": null,
    "products": null,
    "credit": 0
}

export default APPLICATION_DATA;
